services:
  # Backend service
  - type: web
    name: q-star-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /api/test

  # Frontend service
  - type: web
    name: q-star-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://q-star-backend.onrender.com 